### ISSUE TITLE
use literate.jl to create markdown versions of the results

### ISSUE THREAD

**Issue by timziebart** [JuliaEnergy/PowerDynamicsExamples#3]
the best thing would probably be, to use that chance to automatically create notebooks using [Literate.jl](https://github.com/fredrikekre/Literate.jl) that are automatically published on [binder](https://mybinder.org/) as well

**Comment by timkittel** [comment]
@antonplietzsch

**Comment by timziebart** [comment]
@antonplietzsch

**Comment by janlisse** [comment]
Jupyter notebooks are now automatically generated via Literate.jl during a Travis-CI build.
All examples now have a binder url where the notebooks could directly be launched.
